---

- name: configure satellite locations
  theforeman.foreman.foreman_location:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organizations: "{{ location | json_query('organizations[*].name') | list }}"
    name: "{{ location.name }}"
    state: "{{ location.state | default(omit) }}"
  loop_control:
    loop_var: location
  loop: "{{ satellite.foreman.locations }}"
  delegate_to: "{{ delegate_host }}"
