---

# Note: setting facts is faster than having yum install satellite for some hosts then yum install satellite-capsule for others
- name: set satellite install packages
  set_fact:
    satellite_packages: satellite
  when:
    - "'satellite' in group_names"

- name: set capsule install packages
  set_fact:
    satellite_packages: satellite-capsule
  when:
    - "'capsule' in group_names"

- name: install packages for satellite/capsule
  yum:
    name: "{{ satellite_packages }}"
    state: present
