---

- name: create custom products
  katello_product:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_initial_organization }}"
    name: "{{ product.name }}"
    gpg_key: "{{ product.content_credential_name }}"
    sync_plan: daily
  loop_control:
    loop_var: product
  with_items:
    - "{{ custom_products }}"
  delegate_to: localhost
