---

- name: create repos for custom products
  theforeman.foreman.katello_repository:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_initial_organization }}"
    state: present
    content_type: "yum"
    name: "{{ repo.1.repo }}"
    product: "{{ repo.1.product }}"
    url: "{{ repo.1.repo_url }}"
    mirror_on_sync: false
    download_policy: immediate
    gpg_key: "{{ repo.1.content_credential_name }}"
  when:
    - repo.1.content_credential is defined
  loop_control:
    loop_var: repo
  loop: "{{ content_views | subelements('repos') }}"
  delegate_to: "{{ delegate_host }}" 
