---

- name: enable Red Hat repos
  katello_repository_set:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_initial_organization }}"
    name: "{{ repo.1.repo }}"
    product: "{{ repo.1.product }}"
    repositories:
    - releasever: "{{ repo.1.releasever | default(omit) }}"
      basearch: "{{ repo.1.basearch | default(omit) }}"
  when:
    - repo.1.content_credential is not defined
  loop_control:
    loop_var: repo
  loop: "{{ content_views | subelements('repos') }}"
  delegate_to: localhost
