---

- name: set initial settings
  foreman_setting:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    name: "{{ setting.name }}"
    value: "{{ setting.value }}"
  loop_control:
    loop_var: setting
  with_items:
    - "{{ foreman_settings }}"
  delegate_to: localhost

