---

- name: push task file to create content view based on number of repos
  template:
    src: templates/create-content-view.yml.j2
    dest: "{{ role_path }}/tasks/create-content-view-{{ content_view.key }}.yml"
  loop_control:
    loop_var: content_view
  loop: "{{ lookup('dict', content_views) }}"
  delegate_to: "{{ delegate_host }}"

- name: include tasks to create content views
  include_tasks: "{{ role_path }}/tasks/create-content-view-{{ content_view.key }}.yml"
  loop_control:
    loop_var: content_view
  loop: "{{ lookup('dict', content_views) }}"

- name: remove task files for creating content views
  file:
    path: "{{ role_path }}/tasks/create-content-view-{{ content_view.key }}.yml"
    state: absent
  loop_control:
    loop_var: content_view
  loop: "{{ lookup('dict', content_views) }}"
  when:
    - remove_content_view_files
  delegate_to: "{{ delegate_host }}"
