---

- name: sync all repos
  block:
    - name: get all repos to sync
      foreman_search_facts:
        username: "{{ satellite_admin_username }}"
        password: "{{ satellite_admin_password }}"
        validate_certs: false
        server_url: "{{ satellite_url }}"
        resource: repositories
      register: repositories_to_sync

    - debug:
        msg: "{{ item.resources.product }}"
      loop:
        - "{{ repositories_to_sync }}"

    - name: kick off repository Sync tasks
      katello_sync:
        username: "{{ satellite_admin_username }}"
        password: "{{ satellite_admin_password }}"
        validate_certs: false
        server_url: "{{ satellite_url }}"
        organization: "{{ satellite_initial_organization }}"
        product: "{{ repo.product.name }}"
        repository:  "{{ repo.name }}"
      loop_control:
        loop_var: repo
      loop:
        - "{{ repositories_to_sync.resources }}"
      async: 999999
      poll: 0
      register: repos_sync

    - name: wait for repos to finish sncing
      async_status:
        jid: "{{ repo_sync_sleeper_item.ansible_job_id }}"
      when: repo_sync.ansible_job_id is defined
      loop_control:
        loop_var: repo_sync
      loop:
        - "{{ reops_sync }}"
      register: async_job_result
      until: async_job_result.finished
      retries: 999
      delay: 10
  delegate_to: localhost
