---

- name: upload manifest to satellite
  theforeman.foreman.katello_manifest:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ item.name }}"
    state: present
    manifest_path: "{{ item.manifest }}"
  loop: "{{ satellite.organizations }}"
  delegate_to: "{{ delegate_host }}"
