---

- name: "upload manifest {{ organization.manifest }} to satellite organization {{ organization.name }}"
  theforeman.foreman.katello_manifest:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ organization.name }}"
    state: present
    manifest_path: "{{ organization.manifest }}"
  delegate_to: "{{ delegate_host }}"
