---

- name: "create lifecycle environments {{ organization | json_query('lifecycle_environments[*].name') | join(', ') }} in organization {{ organization.name }}"
  theforeman.foreman.katello_lifecycle_environment:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ organization.name }}"
    name: "{{ lifecycle_environment.name }}"
    prior: "{{ lifecycle_environment.prior }}"
    description: "{{ lifecycle_environment.description | default(omit) }}"
  loop_control:
    loop_var: lifecycle_environment
  loop: "{{ organization.lifecycle_environments }}"
  delegate_to: "{{ delegate_host }}"
