---

- name: push task files to create composite content views
  template:
    src: templates/create-composite-content-view.yml.j2
    dest: "{{ role_path }}/tasks/create-composite-content-view-{{ composite_content_view.key }}.yml"
  loop_control:
    loop_var: composite_content_view
  loop: "{{ lookup('dict', composite_content_views) }}"
  delegate_to: "{{ delegate_host }}"

- name: include tasks to create composite content views
  include_tasks: "{{ role_path }}/tasks/create-composite-content-view-{{ composite_content_view.key }}.yml"
  loop_control:
    loop_var: composite_content_view
  loop: "{{ lookup('dict', composite_content_views) }}"

- name: remove task files for creating composite content views
  file:
    path: "{{ role_path }}/tasks/create-composite-content-view-{{ composite_content_view.key }}.yml"
    state: absent
  loop_control:
    loop_var: composite_content_view
  loop: "{{ lookup('dict', composite_content_views) }}"
  when:
    - remove_content_view_files
  delegate_to: "{{ delegate_host }}"
