---

- name: create satellite cert directory for capsule
  file:
    path: "/root/capsule-certificates/{{ inventory_hostname }}"
    state: directory
  register: generate_certs
  delegate_to: "{{ parent_satellite }}"

- name: generate capsule certificates
  shell: >-
    capsule-certs-generate
    --forman-proxy-fqdn "{{ ansible_fqdn }}"
    --certs-tar "/root/capsule-certificates/{{ inventory_hostname }}.tar"
    --foreman-proxy-cname "{{ satellite_loadbalanced_dns }}"
  register: cert_generate_output
  delegate_to: "{{ parent_satellite }}"
