---

#- name: map repo labels to repo name/product
#  shell: hammer repository list --

- theforeman.foreman.foreman_search_facts:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    resource: repository_sets
    params:
     organization_id: 1
     enabled: 1
     search: 'content_label=rhel-7-server-rpms'
  register: repositories
  delegate_to: "{{ delegate_host }}"

- debug:
    msg: "{{ item }}"
#    msg: "{{ item.1.label }}"
#    msg: "{{ item.0.content_label }} {{ item.1.1.label }}"
#  when:
#    - item.0.content_label == item.1.1.label
#    - organization.name in item.0.relative_path
  loop: "{{ repositories.resources | json_query('repositories[*]') }}"
#  loop: "{{ repositories.resources | product(organization.content_views | subelements('repos')) | product(repositories.resources | json_query('repositories[*]')) | list }}"
#  loop: "{{ organization.content_views | subelements('repos') | product(repositories.resources) | list }}"
#  loop: "{{ organization.content_views | subelements('repos') }}"


- name: create content view cv-server-rhel7
  theforeman.foreman.katello_content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    validate_certs: false
    server_url: "https://satellite01.josh.lab.msp.redhat.com"
    organization: "josh"
    name: "cv-server-rhel7"
    repositories:
      - label: "rhel-7-server-rpms"
  delegate_to: localhost
  register: publish_content_view

