---

- name: set repos for capsule version "{{ capsule.version }}"
  set_fact:
    install_repos: "{{ common_repos + capsule_repos + maintenance_repos }}"
  when:
    - capsule.version != 'beta'

- name: set repos for capsule beta
  set_fact:
    install_repos: "{{ common_repos + capsule_beta_repos + maintenance_beta_repos }}"
  when:
    - capsule.version == 'beta'

- name: enable install repos
  rhsm_repository:
    name: "{{ repo }}"
    state: enabled
  loop_control:
    loop_var: repo
  loop:
    - "{{ install_repos }}"

- name: get other enabled repos
  shell: subscription-manager repos --list-enabled | grep 'Repo ID' | awk '{print $3}'
  register: enabled_repos
  changed_when: false
  check_mode: false

- name: disable unneeded repos
  rhsm_repository:
    name: "{{ repo }}"
    state: disabled
  when:
    - repo not in install_repos
  loop_control:
    loop_var: repo
  with_items:
    - "{{ enabled_repos.stdout_lines }}"
